export const monsters = [
  {
    id:0,
    name:"Besaid",
   monsters: [
     {name:"Dingo", count:0},
     {name:"Condor", count:0},
     {name:"Water Flan", count:0},
   ]
  },
  {
    id:1,
    name:"Kilika",
    monsters: [
     {name:"Dinonix", count:0},
     {name:"Killer Bee", count:0},
     {name:"Yellow Element", count:0},
     {name:"Ragora", count:0},
   ]
  },
  {
    id:2,
    name:"Mi'ihen Highroad",
   monsters: [
     {name:"Mi'ihen Fang", count:0},
     {name:"Ipiria", count:0},
     {name:"Floating Eye", count:0},
     {name:"White Element", count:0},
     {name:"Raldo", count:0},
     {name:"Vouivre", count:0},
     {name:"Bomb", count:0},
     {name:"Dual Horn", count:0},
   ]
  },
  {
    id:3,
    name:"Mushroom Rock Road",
   monsters: [
     {name:"Raptor", count:0},
     {name:"Gandarewa", count:0},
     {name:"Thunder Flan", count:0},
     {name:"Red Element", count:0},
     {name:"Lamashtu", count:0},
     {name:"Funguar", count:0},
     {name:"Garuda", count:0},
   ]
  },
  {
    id:4,
    name:"Djose",
  monsters: [
     {name:"Garm", count:0},
     {name:"Simurgh", count:0},
     {name:"Bite Bug", count:0},
     {name:"Snow Flan", count:0},
     {name:"Bunyip", count:0},
     {name:"Basilisk", count:0},
     {name:"Ochu", count:0},
   ]
  },
  {
    id:5,
    name:"Thunder Plains",
  monsters: [
     {name:"Melusine", count:0},
     {name:"Aerouge", count:0},
     {name:"Buer", count:0},
     {name:"Gold Element", count:0},
     {name:"Kusiraqqu", count:0},
     {name:"Larva", count:0},
     {name:"Iron Giant", count:0},
     {name:"Quactuar", count:0},
   ]
  },
  {
    id:6,
    name:"Macalania",
  monsters: [
     {name:"Snow Wolf", count:0},
     {name:"Iguion", count:0},
     {name:"Wasp", count:0},
     {name:"Evil Eye", count:0},
     {name:"Ice Flan", count:0},
     {name:"Blue Element", count:0},
     {name:"Murussu", count:0},
     {name:"Mafdet", count:0},
     {name:"Xiphos", count:0},
     {name:"Chimera", count:0},
   ]},
  {
    id:7,
    name:"Bikanel",
  monsters: [
     {name:"Sand Wolf", count:0},
     {name:"Alcyone", count:0},
     {name:"Mushusuu", count:0},
     {name:"Zu", count:0},
     {name:"Sand Worm", count:0},
     {name:"Cactuar", count:0},
   ]},
  {
    id:8,
    name:"Calm Lands",
  monsters: [
     {name:"Skoll", count:0},
     {name:"Nebiros", count:0},
     {name:"Flame Flan", count:0},
     {name:"Shred", count:0},
     {name:"Anacondaur", count:0},
     {name:"Ogre", count:0},
     {name:"Coeurl", count:0},
     {name:"Chimera Brain", count:0},
     {name:"Malboro", count:0},
   ]},
  {
    id:9,
    name:"Sunken Cave",
  monsters: [
     {name:"Yowie", count:0},
     {name:"Imp", count:0},
     {name:"Dark Element", count:0},
     {name:"Nidhogg", count:0},
     {name:"Thorn", count:0},
     {name:"Valaha", count:0},
     {name:"Epaaj", count:0},
     {name:"Ghost", count:0},
     {name:"Tonberry", count:0},
   ]},
  {
    id:10,
    name:"Gagazet",
  monsters: [
     {name:"Bandersnatch", count:0},
     {name:"Grat", count:0},
     {name:"Bashura", count:0},
     {name:"Grenade", count:0},
     {name:"Splasher", count:0},
     {name:"Achelous", count:0},
     {name:"Maelspike", count:0},
     {name:"Ahriman", count:0},
     {name:"Grendel", count:0},
    {name:"Mandragora", count:0},
    {name:"Behemoth", count:0},
    {name:"Dark Flan", count:0},
   ]},
  {
    id:11,
    name:"Sin",
  monsters: [
     {name:"Exoray", count:0},
     {name:"Wraith", count:0},
     {name:"Gemini A", count:0},
     {name:"Gemini B", count:0},
     {name:"Demonolith", count:0},
     {name:"Great Malboro", count:0},
     {name:"Barbatos", count:0},
     {name:"Adamantoise", count:0},
     {name:"Behemoth King", count:0},
   ]},
  {
    id:12,
    name:"Omega Dungeon",
  monsters: [
     {name:"Zaurus", count:0},
     {name:"Floating Death", count:0},
     {name:"Black Element", count:0},
     {name:"Halma", count:0},
     {name:"Puroboros", count:0},
     {name:"Spirit", count:0},
     {name:"Maches", count:0},
     {name:"Master Coeurl", count:0},
     {name:"Master Tonberry", count:0},
    {name:"Varuna", count:0},
   ]},
  {
    id:13,
    name:"Original Monsters",
  monsters: [
     {name:"Stratoavis",count:0},
    {name:"Malboro Menace", count:0}, 
    {name:"Kottos", count:0},
    {name:"Couerlregina", count:0},
    {name:"Jormungand", count:0},
    {name:"Cactuar King", count:0}, 
    {name:"Espada", count:0},
    {name:"Abyss Worm", count:0},
    {name:"Chimerageist", count:0},
    {name:"Don Tonberry", count:0},
    {name:"Catoblepas", count:0},
    {name:"Abaddon", count:0},
    {name:"Vorban", count:0},
     {name:"Greater Sphere", count:0},
     {name:"Th'uban", count:0},
     {name:"Earth Eater", count:0},
     {name:"Catastrophe", count:0},
     {name:"Shinryu", count:0},
     {name:"Neslug", count:0},
     {name:"Ultima Buster", count:0},
     {name:"Nemesis", count:0},
    
   ]},
  
];